name: Go
on:
  pull_request:
jobs:
  go1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.18.0'
      - run: go version
  go2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.18.x'
      - run: go version
