name: Go
on:
  pull_request:
jobs:
  go1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.23.2'
      - run: go version
  go2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.23.2.x'
      - run: go version
